### Create and Update Profile
POST http://localhost:5000/api/profile HTTP/1.1
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzNGE4MzIyYzJjZDkzZDYwZDEwOWI4In0sImlhdCI6MTU2MzczMjAxOCwiZXhwIjoxNTY0MDkyMDE4fQ.acpqDbJoIjSmg0zAJQJby3BkC0gxIL7TvhxKwmuLJpE

{
    "company": "TechSoft INC",
    "status": "Junior Developer",
    "skills": "HTML , JS, Python"
}

### Get logged in user profile
GET http://localhost:5000/api/profile/me HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzNDgwYjcwZTZmZWIyZjE1Y2RlYTA0In0sImlhdCI6MTU2MzcyMTkxMSwiZXhwIjoxNTY0MDgxOTExfQ.hkvFosaGPv3o4bzQysjDmZmmb39V0dQNhLuPNCg5WPY

### Get all profiles
GET http://localhost:5000/api/profile HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzNDgwYjcwZTZmZWIyZjE1Y2RlYTA0In0sImlhdCI6MTU2MzcyMTkxMSwiZXhwIjoxNTY0MDgxOTExfQ.hkvFosaGPv3o4bzQysjDmZmmb39V0dQNhLuPNCg5WPY

### Get profile by user ID
GET http://localhost:5000/api/profile/user/5d347b5fa592012d53aa HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzNDk4ODA2YWRmMTUzOGU1ODA3ODA0In0sImlhdCI6MTU2MzcyODI0OSwiZXhwIjoxNTY0MDg4MjQ5fQ.TD75QBuSY2fRba4PyKS8OqIzU6E2f4Wj_ndo_yQpELs

### Delete user profile
DELETE  http://localhost:5000/api/profile HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzNGE3ZDAyYzJjZDkzZDYwZDEwOWI2In0sImlhdCI6MTU2MzczMTkyMSwiZXhwIjoxNTY0MDkxOTIxfQ.OG3rBDRPc7F06ZeMBZ9xaiTmMhoxDAbrqZhrYf97fYs

### Add profile experience
PUT http://localhost:5000/api/profile/experience HTTP/1.1
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzNGE4MzIyYzJjZDkzZDYwZDEwOWI4In0sImlhdCI6MTU2MzczMjAxOCwiZXhwIjoxNTY0MDkyMDE4fQ.acpqDbJoIjSmg0zAJQJby3BkC0gxIL7TvhxKwmuLJpE

{
    "title": "Web Developer",
    "company": "Apple inc",
    "location": "Toronto, ON",
    "from": "8-10-2010",
    "current": true,
    "description": "Full Stack Web Dev"
}

### DELETE profile experience
DELETE http://localhost:5000/api/profile/experience/5d34a94c4a85f13dcde08d1f HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzNGE4MzIyYzJjZDkzZDYwZDEwOWI4In0sImlhdCI6MTU2MzczMjAxOCwiZXhwIjoxNTY0MDkyMDE4fQ.acpqDbJoIjSmg0zAJQJby3BkC0gxIL7TvhxKwmuLJpE

### Add profile education
PUT http://localhost:5000/api/profile/education HTTP/1.1
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzNGE4MzIyYzJjZDkzZDYwZDEwOWI4In0sImlhdCI6MTU2MzczMjAxOCwiZXhwIjoxNTY0MDkyMDE4fQ.acpqDbJoIjSmg0zAJQJby3BkC0gxIL7TvhxKwmuLJpE

{
    "school": "Northern Essex College",
    "degree": "Associates Degree",
    "fieldofstudy": "Computer Science",
    "from": "8-2-2003",
    "to": "3-4-2005",
    "description": "Got Associates in computer science"
}

### DELETE profile experience
DELETE http://localhost:5000/api/profile/education/5d34b49d4a7b9f414d8b405c HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzNGE4MzIyYzJjZDkzZDYwZDEwOWI4In0sImlhdCI6MTU2MzczMjAxOCwiZXhwIjoxNTY0MDkyMDE4fQ.acpqDbJoIjSmg0zAJQJby3BkC0gxIL7TvhxKwmuLJpE
