### Register
POST http://localhost:5000/api/users HTTP/1.1
content-type: application/json

{
    "name": "Steve Smith",
    "email": "steve@gmail.com",
    "password": "123456"
}

### Login
POST http://localhost:5000/api/auth HTTP/1.1
content-type: application/json

{
    "email": "steve@gmail.com",
    "password": "123456"
}

#### Get auth user
GET http://localhost:5000/api/auth HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzNDgwYjcwZTZmZWIyZjE1Y2RlYTA0In0sImlhdCI6MTU2MzcyMTkxMSwiZXhwIjoxNTY0MDgxOTExfQ.hkvFosaGPv3o4bzQysjDmZmmb39V0dQNhLuPNCg5WPY
